### PR TITLE
Code was sorted into primary logical structures. Some sorting still needed though.

### PR DESCRIPTION
**Pull request by jfsehuanes**
Code was sorted into several scripts, each containing a logical structure. Main folders were also renamed and a recycle_bin folder was created for code we are not totally sure if we want to get rid of. There is still sorting to be done, though. Good candidates are all plotting functions; pack them into a separate script!

### CODE REVIEW

**Comment by jgrewe** [comment]
Hi Juan, there is no need to close the pull-request, just go on from where you are and push to your branch. Github will notice this and the pull-request will include all your latest commits.

**Comment by jgrewe** [comment]
I agree with Fabian, do not use a recycle bin, If you want you may chose to tag the current state

```
git tag before_restructure
```

should do the trick. You can later chose to checkout the tag, if you need.

**Comment by janscience** [comment]
Solange die Jungs noch mitten im umstrukturieren sind, wuerde ich den 
recycle bin erstmal lassen. Erst wenn wir durch sind und auf den recycle 
bin schauen und da nichts mehr finden, was wir aufheben wollen, dann 
kann der weg, oder getaged werden. Sonst erinnert sich keiner mehr 
daran, was noch fehlt - oder?

**Comment by fabiansinz** [comment]
I understood @jfsehuanes  that code in recycle bin is basically staged for deletion, not code that needs to be restructured. I don't see the value in keeping that under version control any further especially when it's easy to look back at the file in the history. 

That said, I think it can stay until the restructuring is done but then should be removed definitely. Usually, if you are not sure whether to delete some code or not, you should delete it.

**Comment by fabiansinz** [comment]
And I also think that unit-tests would be very helpful. Especially in cases where the code is restructured it is a very helpful tool to make sure that everything runs as intended and nothing that is still needed got deleted.

**Pull request closed without merging**
